pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage ('SCM checkout'){
            steps{
                cleanWs()
                git branch: 'main', url: 'https://github.com/comrider/springboot-app.git'
            }
        }
        stage("build & SonarQube analysis"){
            steps{
                withSonarQubeEnv('sonarqube') {
                    sh 'mvn clean package sonar:sonar'
                }
            }
        }
        stage("Quality Gate") {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('unit test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('integration test'){
            steps {
                sh 'mvn verify  -DskipUnitTests'
            }
        }
        stage('code analysis with checkstyle'){
            steps{
                sh 'mvn checkstyle:checkstyle'
            }
            post {
                success{
                    echo "Generated Analysis Result"
                }
            }
        }
        stage('build jar file'){
            steps{
                sh 'mvn clean install '
            }
        }
    }
}